### ISSUE TITLE
to.be.true and to.be.false do not indicate line number when failing

### ISSUE THREAD

**Issue by vtsatskin** [chaijs/chai#437]
The following code:

```js
describe('Test feature', function() {
  it('should raise line number', function() {
    expect(true).to.be.false;
  });
});
```

Yields the failure:
```js
Chrome 42.0.2311 (Mac OS X 10.10.3) Test feature should raise line number FAILED
        AssertionError: expected true to be false
```

This can be difficult to debug where your failure is in a test suite if no line number or file is given.

However, if you run the following code:

```js
describe('Test feature', function() {
  it('should raise line number', function() {
    expect(true).to.equal(false);
  });
});
```

The line number is reported:

```js
Chrome 42.0.2311 (Mac OS X 10.10.3) Test feature should raise line number FAILED
        AssertionError: expected true to be false
            at Context.<anonymous> (/test.js:3:27)
```

## Version Information

```js
mocha@2.1.0
karma@0.12.31 
karma-chai@0.1.0 
karma-mocha@0.1.10 
```

**Comment by keithamus** [comment]
Hey @vtsatskin thanks for the issue.

Can you try setting `chai.config.includeStack = true;` and seeing if that fixes the problem?

Thanks

**Comment by vtsatskin** [comment]
Will do! Thanks

**Comment by danielrentz** [comment]
I stumbled over the same problem, as an example I am getting:

expect(false).to.be.true;

AssertionError: expected false to be true
    at ####/ui/node_modules/chai/chai.js:873
    at ####/ui/node_modules/chai/chai.js:1176
    at ####/ui/node_modules/chai/chai.js:3549

expect(false).to.equal(true);

AssertionError: expected false to equal true
    at ####/ui/node_modules/chai/chai.js:873
    at assertEqual (####/ui/node_modules/chai/chai.js:1386)
    at ####/ui/node_modules/chai/chai.js:3627
    at ####/ui/build/spec/test_spec.js:20

**Comment by wes-r** [comment]
Also hit this recently running under `karma`. For me, all assertions (TDD or BDD) would result in a no stack trace. This is currently forcing my hand into using jasmine :(

**Comment by meeber** [comment]
Hi @wes-r. I don't suppose you have a repo I can clone to take a look at this issue?

**Comment by wes-r** [comment]
@meeber unfortunately no :(, next week I can try and isolate this and see if I can get you a repo.

From package.json (basically latest of everything):
```
   "chai": "3.5.0",
    "mocha": "2.4.5",
    "karma-mocha": "0.2.2",
    "karma": "^0.13.22",
    "karma-coverage": "^0.4.2",
    "karma-ng-html2js-preprocessor": "^0.2.2",
    "karma-phantomjs-launcher": "^0.2.0",
```

And changing the above chai version to v2 gets a stack trace.

**Comment by meeber** [comment]
Ahhh I just reproduced this.

`err.stack` is `undefined` for a test run through karma/phantomjs even though the same test correctly displays the stack when run directly through node.

Will investigate!

**Comment by meeber** [comment]
@wes-r I believe this is fixed [here](https://github.com/chaijs/assertion-error/pull/5)

Could you try an `npm install https://github.com/chaijs/assertion-error` in your repo and see if you start getting stack traces?

**Comment by wes-r** [comment]
@meeber :( still no luck

I've setup https://github.com/wes-r/karma-mocha-chai as an example of the problem.

Note I'm running this with **Node v4.4.3**

```
git clone git@github.com:wes-r/karma-mocha-chai.git
cd karma-mocha-chai
npm install
karma start --single-run
```

Results in:
```
30 04 2016 10:15:38.010:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
30 04 2016 10:15:38.024:INFO [launcher]: Starting browser PhantomJS
30 04 2016 10:15:38.916:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#WSCYUH6nddko8TQlAAAA with id 33137121
PhantomJS 2.1.1 (Mac OS X 0.0.0) test assertions work should print stack on error FAILED
	expected false to be true
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.01 secs / 0.002 secs)
```

Another clue: If you uncomment `/assertThatDontExist();` in the test, you'll correctly see the stack trace for the JS error.

**Comment by wes-r** [comment]
Ah, I mis-understood the fix using `assertion_error`. When I add those lines to my node_modules/chai/chai.js, I start to get stack traces.. but ugly ones:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) test assertions work should print stack on error FAILED
	expected false to be true
	AssertionError@/Users/Wes/kapow/karma-mocha-chai/node_modules/chai/chai.js:5554:24
	assert@/Users/Wes/kapow/karma-mocha-chai/node_modules/chai/chai.js:206:31
	/Users/Wes/kapow/karma-mocha-chai/node_modules/chai/chai.js:567:16
	addProperty@/Users/Wes/kapow/karma-mocha-chai/node_modules/chai/chai.js:4240:33
	isTrue@/Users/Wes/kapow/karma-mocha-chai/node_modules/chai/chai.js:2483:31
	/Users/Wes/kapow/karma-mocha-chai/tests/assert_test.js:4:18
```

**Comment by meeber** [comment]
@wes-r Yeah, once the new version of assertion_error gets released, then those long stack traces will start showing up for PhantomJS tests. 

Unfortunately, getting concise stack traces will require a polyfill for V8's `Error.captureStackTrace`. Although I see a couple of polyfills on npm, none of them accept the second parameter which is key to producing the concise traces. I'm not familiar enough with the innerworkings of V8's `Error.captureStackTrace` to speculate on the feasibility or level-of-effort to create a full polyfill, but it might be worth exploring.

@keithamus @lucasfcosta would love to hear your thoughts on this.

**Comment by wes-r** [comment]
Was able to cleanup output using https://github.com/davidosomething/karma-mocha-clean-reporter

**Comment by meeber** [comment]
The newer version of assertion-error was released. Closing!
